name: Generate Repo JSON

on:
  workflow_dispatch:
  push:
    paths:
      - 'data/**'
      - 'generate_repo_json.py'
      - 'fix_cgbi.py'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow

      - name: Fix PNGs
        run: python fix_cgbi.py

      - name: Commit fixed PNGs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/*/*.png
          git commit -m "fix PNGs" || echo "no PNG changes"
          git push

      - name: Run script
        run: python generate_repo_json.py

      - name: Commit repo.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add repo.json
          git commit -m "update repo.json" || echo "no changes"
          git push
